## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: AspNetMesh
  properties:
    services:
      - name: WebFrontEnd
        properties:
          description: WebFrontEnd description.
          osType: Windows
          codePackages:
            - name: WebFrontEnd
              image: webfrontend:dev
              endpoints:
                - name: WebFrontEndListener
                  port: 80
              environmentVariables:
                - name: ApplicationInsights:InstrumentationKey
                  value: "47317915-7dab-44ee-8055-c57a462f571b"
                - name: ApiHostPort
                  value: 80
                - name: ToDoServiceName
                  value: ToDoService
              resources:
                requests:
                  cpu: "[parameters('WebFrontEnd_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: AspNetMeshNetwork
              endpointRefs:
                - name: WebFrontEndListener
